#!/bin/bash
# set -x
NUMBER_FILE=".build.number"

script_args=()
while [ $OPTIND -le "$#" ]
do
    if getopts f:i: option
    then
        case $option
        in
        f) 
            NUMBER_FILE=${OPTARG}
            ;;
        esac
    else
        script_args+=("${!OPTIND}")
        ((OPTIND++))
    fi
done
if ! test -f ${NUMBER_FILE}; then echo "0" > ${NUMBER_FILE};  fi
n=$(cat $NUMBER_FILE)
if [ "${script_args[0]}" = "inc" ]; then
    let n++
    echo $n > ${NUMBER_FILE}
fi
echo $n
