#!/bin/bash
# set -x
NUMBER_FILE="build.number.kleio"
n=$(cat $NUMBER_FILE)

script_args=()
while [ $OPTIND -le "$#" ]
do
    if getopts f:i: option
    then
        case $option
        in
        f) 
            NUMBER_FILE=${OPTARG}
            if ! test -f ${NUMBER_FILE}; then echo "0" > ${NUMBER_FILE};  fi
            n=$(cat $NUMBER_FILE)
            ;;
        esac
    else
        script_args+=("${!OPTIND}")
        ((OPTIND++))
    fi
done

if [ "${script_args[0]}" = "inc" ]; then
    let n++
    echo $n > ${NUMBER_FILE}
fi
echo $n
