version: "3.8"
services:
  kleio:
    # includes git
    image: ${KLEIO_SERVER_IMAGE:-timelinkserver/kleio-server:latest}

    # Run under current user otherwise in linux systems sources files and translations are owned by root
    # requires export of current user and group
    #       export KLEIO_USER=$(id -u):$(id -g)
    user: ${KLEIO_USER}

    volumes:
      - ${KLEIO_HOME_DIR}:/kleio-home:cached
    ports:
      - "${KLEIO_EXTERNAL_PORT:-8088}:${KLEIO_SERVER_PORT-8088}"
    environment:
      - KLEIO_DEBUG
      - KLEIO_SERVER_WORKERS
      - KLEIO_SERVER_PORT
      - KLEIO_ADMIN_TOKEN
    restart: unless-stopped