"""Data models for Kleio inference rules."""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Callable, Optional
from enum import Enum


class ConditionType(Enum):
    """Types of conditions in inference rules."""
    SEQUENCE = "sequence"      # Match any sequence of ancestor groups
    GROUP = "group"            # Match specific group by name
    EXTENDS = "extends"        # Match group inheriting from base class
    ELEMENT = "element"        # Extract element value
    CLAUSE = "clause"          # Arbitrary predicate


class ActionType(Enum):
    """Types of actions in inference rules."""
    RELATION = "relation"      # Generate a relationship
    ATTRIBUTE = "attribute"    # Generate an attribute
    NEW_SCOPE = "newscope"     # Reset matching context


@dataclass
class Condition:
    """A single condition in an inference rule.
    
    Conditions are matched against groups in a path from root to leaf.
    
    Examples:
        - sequence(_): Matches any sequence of groups (including empty)
        - extends(actorm, N): Matches a group that extends 'actorm', binds ID to N
        - group(pai, P): Matches a group named 'pai', binds ID to P
    """
    type: ConditionType
    group_name: str = ""       # For GROUP/EXTENDS conditions
    element_name: str = ""     # For ELEMENT conditions
    bind_var: str = ""         # Variable name to bind matched value
    predicate: Optional[Callable] = None  # For CLAUSE conditions
    negate: bool = False       # Negate the condition


@dataclass
class Action:
    """An action to execute when rule conditions match.
    
    Actions generate relations or attributes based on variable bindings
    from matched conditions.
    
    Examples:
        - relation(parentesco, pai, father_id, child_id): 
          Creates a "pai" (father) relationship
        - attribute(entity_id, ec, c):
          Sets attribute "ec" (marital status) to "c" (married)
    """
    type: ActionType
    relation_type: str = ""    # For RELATION: type of relation (e.g., "parentesco")
    relation_value: str = ""   # For RELATION: value (e.g., "pai")
    origin_var: str = ""       # Variable name for origin entity
    dest_var: str = ""         # Variable name for destination entity
    attr_entity_var: str = ""  # For ATTRIBUTE: entity variable
    attr_type: str = ""        # For ATTRIBUTE: attribute type
    attr_value: str = ""       # For ATTRIBUTE: attribute value (can be literal or var)
    attr_value_is_var: bool = False  # If True, attr_value is a variable name to resolve


@dataclass
class InferenceRule:
    """A complete inference rule with conditions and actions.

    Rules follow the pattern: if [conditions] then [actions]

    Two forms are supported:

    1. Single-path (default): ``conditions`` is a flat ordered list of
       conditions matched against one root-to-node path.

       Example:
           if [sequence(_), extends(actorm, N), pai(P)]
           then relation(parentesco, pai, P, N)

       This generates a father relationship from P (pai) to N (child).

    2. Multi-path (cross-path ``and``): ``condition_paths`` is a list of
       sub-paths, each a list of conditions. Every sub-path must match
       somewhere in the group tree, and the resulting bindings must
       unify (shared ``bind_var`` names must agree). For each consistent
       joint binding the actions fire once.

       Example (Prolog: ``if [seq,extends(actorm,N),pai(P)] and
       [seq,extends(actorm,N),mae(M)] then ...``)::

           condition_paths = [
               [SEQUENCE, EXTENDS(actorm, child_id), GROUP(pai, father_id)],
               [SEQUENCE, EXTENDS(actorm, child_id), GROUP(mae, mother_id)],
           ]

       Here ``child_id`` is the join variable: both sub-paths must bind
       it to the same actorm id. When non-empty, ``condition_paths``
       takes precedence and ``conditions`` is ignored by the engine.
    """
    name: str
    conditions: list[Condition] = field(default_factory=list)
    actions: list[Action] = field(default_factory=list)
    condition_paths: list[list[Condition]] = field(default_factory=list)
    priority: int = 0
    description: str = ""


@dataclass
class GeneratedRelation:
    """A relation generated by inference.
    
    Relations connect two entities with a typed relationship.
    
    Example:
        rel_type="parentesco", value="pai", origin_id="p1", dest_id="a1"
        Means: entity p1 is the father (pai) of entity a1
    """
    rel_type: str              # e.g., "parentesco"
    value: str                 # e.g., "pai"
    origin_id: str             # ID of the origin entity
    dest_id: str               # ID of the destination entity
    source_rule: str = ""      # Name of the rule that generated this

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, GeneratedRelation):
            return NotImplemented
        return (self.rel_type == other.rel_type and 
                self.value == other.value and
                self.origin_id == other.origin_id and 
                self.dest_id == other.dest_id)

    def __hash__(self) -> int:
        return hash((self.rel_type, self.value, self.origin_id, self.dest_id))


@dataclass
class GeneratedAttribute:
    """An attribute generated by inference.
    
    Attributes assign a value to an entity's property.
    
    Example:
        entity_id="p1", attr_type="ec", attr_value="c"
        Means: entity p1 has marital status (ec) = married (c)
    """
    entity_id: str             # ID of the entity
    attr_type: str             # Attribute type
    attr_value: str            # Attribute value
    source_rule: str = ""

    def __eq__(self, other: object) -> bool:
        if not isinstance(other, GeneratedAttribute):
            return NotImplemented
        return (self.entity_id == other.entity_id and 
                self.attr_type == other.attr_type and
                self.attr_value == other.attr_value)

    def __hash__(self) -> int:
        return hash((self.entity_id, self.attr_type, self.attr_value))


@dataclass
class InferenceResults:
    """Results from applying inference rules.
    
    Collects all generated relations and attributes, with duplicate prevention.
    """
    relations: list[GeneratedRelation] = field(default_factory=list)
    attributes: list[GeneratedAttribute] = field(default_factory=list)
    
    def add_relation(self, rel: GeneratedRelation) -> None:
        """Add a relation, avoiding duplicates."""
        if rel not in self.relations:
            self.relations.append(rel)
    
    def add_attribute(self, attr: GeneratedAttribute) -> None:
        """Add an attribute, avoiding duplicates."""
        if attr not in self.attributes:
            self.attributes.append(attr)
    
    def merge(self, other: InferenceResults) -> None:
        """Merge another results set into this one."""
        for rel in other.relations:
            self.add_relation(rel)
        for attr in other.attributes:
            self.add_attribute(attr)
