?-consult(basicio).
?-consult(clioUtil).
?-consult(compatibilitySWI).
?-consult(dataCDS).
?-consult(dataCode).
?-consult(dataDictionary).
?-consult(dataSyntax).
?-consult(errors).
?-consult(exputil).
?-consult(inference).
?-consult(mappings).
?-consult(gactoxml).
?-consult(externals).
?-consult(lexical).
?-consult(struCode).
?-consult(struSyntax).
?-consult(topLevel).
?-consult(utilities).
?-consult(verif).
?-consult(clioPP).
?-consult(swiShell).

